### ISSUE TITLE
Explicit Docs Link

### ISSUE THREAD

**Issue by blackary** [intake/intake-sql#14]
It took me a while to find the link to the docs -- would you be willing to set https://intake-sql.readthedocs.io/ as the url for the repo, or put an explicit link in the README? I discovered that clicking the badge goes to the docs, but it took me a while to find that.

**Comment by martindurant** [comment]
I have set it as the "website URL" of the repo. Is that what you had in mind?

**Comment by martindurant** [comment]
Hm, it seems to require the https://

**Comment by blackary** [comment]
For whatever reason, it now shows as a clickable link for me. Thanks! I think this makes the docs much easier to find.
