### ISSUE TITLE
Does not support sqlalchemy 2?

### ISSUE THREAD

**Issue by mjmare** [intake/intake-sql#19]
I'm getting an error: TypeError: MetaData.__init__() got an unexpected keyword argument 'bind'
Reverting to sqlalchemy 1.4 solved the problem.

**Comment by martindurant** [comment]
I am not immediately sure! I will try to look into it soon.

**Comment by martindurant** [comment]
Actually, intake-sql has a version limit on sqlalchemy not allowing 2 or above. I will look into updating this and making a release this week.
