### ISSUE TITLE
Reading queries with subqueries doesn't work.

### ISSUE THREAD

**Issue by miloszbednarzak** [intake/intake-sql#3]
When i'm trying to create new data source with intake.open_sql() with e.g.
`select * from table where user_id in (select id from users where id in (123, 124))` 
it causes:
`InternalError: (pymysql.err.InternalError) (1059, "Identifier name 'select * from table where user_id in (select id from users where id in (123, 124))' is too long"`
or it produces
`ProgrammingError: (pymysql.err.ProgrammingError) (1103, "Incorrect table name..."`
in different queries involving subqueries.

I think it might be bug concerning treating statement in bracket as table.

**Comment by martindurant** [comment]
Can you try using `AS` to alias the subqueries?

**Comment by miloszbednarzak** [comment]
Unfortunately doesn't work either. 
Also as I queried `select column1, column2 from table where column1 = 12` I also get `InternalError: (1059...`
I can also add that I use MySQL.

**Comment by martindurant** [comment]
Any further progress here? Since I don't really know the problem well or have any further suggestions, I would close this.
